module SkelLambdaNat where

-- Haskell module generated by the BNF converter

import AbsLambdaNat
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transId :: Id -> Result
transId x = case x of
  Id string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Prog exps -> failure x
transExp :: Exp -> Result
transExp x = case x of
  EAbs id exp -> failure x
  EIf exp1 exp2 exp3 exp4 -> failure x
  ELet id exp1 exp2 -> failure x
  ERec id exp1 exp2 -> failure x
  EHd exp -> failure x
  ETl exp -> failure x
  ELE exp1 exp2 -> failure x
  EPlus exp1 exp2 -> failure x
  EMinus exp1 exp2 -> failure x
  ETimes exp1 exp2 -> failure x
  EApp exp1 exp2 -> failure x
  ENil -> failure x
  ECons exp1 exp2 -> failure x
  EInt integer -> failure x
  EVar id -> failure x
  EFix exp -> failure x

